---
title: "Data Manipulation"
author: "Yang Gao"
date: "9/27/2021"
output: github_document
---

```{r}
library(tidyverse)
```

## load in the FAS litters data

```{r}
litters_df=read_csv("./datasets/data_import_examples/FAS_litters.csv")
litters_df = janitor :: clean_names(litters_df)
```

## `select`

choose some columns and not others.

```{r}
select(litters_df, group, litter_number)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)
```


```{r}
select(litters_df, -litter_number)
```

Renaming columns...
```{r}
select(litters_df, GROUP=group, LITTER_Number= litter_number)
```

```{r}
rename(litters_df,GROUP=group, LITTER_Number= litter_number)
```

select helpers
```{r}
select(litters_df, starts_with("gd"))
```

```{r}
select(litters_df, litter_number, everything())
```

```{r}
relocate(litters_df, litter_number)
```


## `filter`
```{r}
filter(litters_df, gd0_weight < 22)
```


```{r}
filter(litters_df, gd0_weight >= 22)
```


```{r}
filter(litters_df, gd_of_birth == 20)
```


```{r}
filter(litters_df, !(gd_of_birth == 20))
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod8" )
```

either in Mod8 or Con7
```{r}
filter(litters_df, group %in% c("Mod8", "Con7"))
```

## `mutate`

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group =  str_to_lower(group)
  )
```


## `arrange`

```{r}
arrange(litters_df, pups_born_alive)
```

## `%>%`
```{r}
litters_data_raw=read_csv("./datasets/data_import_examples/FAS_litters.csv")

litters_clean_names = janitor::clean_names(litters_data_raw)
litters_data_selected = select(litters_clean_names, gd0_weight:pups_survive)
litters_mutaed= mutate(litters_data_selected, wt_gain = gd18_weight - gd0_weight)
litters_without_missing = drop_na(litters_mutaed, gd0_weight)
litters_without_missing
```

```{r}
litters_df = 
  read_csv("./datasets/data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(gd0_weight:pups_survive) %>% 
  mutate(wt_gain = gd18_weight - gd0_weight) %>% 
  drop_na(gd0_weight)

litters_df
```
































