---
title: "Simple document"
output: github_document
---

I'm an R Markdown document! 



```{r,echo= FALSE, message=FALSE}
library(tidyverse)
library(janitor)
```
## Import some data

I want to import `FAS_litters.csv`

```{r}
litters_data = read_csv(file = "./datasets/data_import_examples/FAS_litters.csv")
```

I imported the data set. need better names

```{r}
names (litters_data)

litters_data= janitor :: clean_names(litters_data)
```
::clean_names means shortcut of janitor package functions

```{r}
litters_data
head(litters_data)
tail(litters_data)
```
```{r,eval=FALSE}
view(litters_data)
```

Here's `skimr`

```{r}
skimr::skim(litters_data)
```


# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r}
samp = rnorm(100)
length(samp)
```

```{r}
litters_data = read_csv ( "./datasets/data_import_examples/FAS_litters.csv")
skip=5
col_names= FALSE
na= "low8"
```
```{r}
litters_data = read_csv(file = "./datasets/data_import_examples/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
```





# Section 2

I can take the mean of the sample, too!
The mean is `r mean(samp)`.




